### ISSUE TITLE
Following "Usage" instructions cause CI failure 

### ISSUE THREAD

**Issue by maxfieldegaj** [thebritican/fetch-latest-release#21]
Usage section of ReadMe should reflect the updated account name for the repo.

From https://github.com/marketplace/actions/fetch-latest-release:
```
steps:
  - id: fetch-latest-release
    uses: **thebritican**/fetch-latest-release@v1
    with:
      github_token: ${{ github.token }}
```
